"""
Reusable AI UI components:
- ai_block: auto-generates a grounded interpretation for one figure/table as soon as it loads
  (cached per content hash; regenerate on demand).
- chat_panel: a per-output chat with conversation memory, grounded in that output's context.

Both are gentle no-ops until an OpenAI API key is entered in the sidebar.
"""
from __future__ import annotations

import hashlib
import json

import streamlit as st

import llm
from theme import clean


def _cfg() -> dict:
    return st.session_state.get("llm") or {}


def enabled() -> bool:
    return bool(_cfg().get("key"))


def auto_on() -> bool:
    return bool(st.session_state.get("ai_auto", True))


def _hash(data) -> str:
    try:
        payload = data.to_dict(orient="records") if hasattr(data, "to_dict") else data
    except Exception:
        payload = str(data)
    return hashlib.md5(json.dumps(payload, default=str, sort_keys=True).encode()).hexdigest()[:12]


def ai_block(block_id: str, title: str, what: str, data) -> None:
    """Grounded interpretation that appears under the output as soon as it loads."""
    cfg = _cfg()
    if not cfg.get("key"):
        st.caption(clean("AI interpretation: add your OpenAI API key in the sidebar to enable a "
                         "plain-language read of this output."))
        return

    model = cfg.get("model", llm.DEFAULT_MODEL)
    h = _hash(data)
    skey = f"aiout_{block_id}"
    cached = st.session_state.get(skey)

    if (cached is None or cached.get("hash") != h) and auto_on():
        with st.spinner("Interpreting..."):
            st.session_state[skey] = {"hash": h, "text": llm.interpret(cfg["key"], model, title, what, data)}
        cached = st.session_state[skey]

    with st.container(border=True):
        st.markdown(f"**AI interpretation - {clean(title)}**")
        if cached and cached.get("hash") == h:
            st.markdown(clean(cached["text"]))
            c1, _ = st.columns([1, 5])
            if c1.button("Regenerate", key=f"regen_{block_id}"):
                with st.spinner("Interpreting..."):
                    st.session_state[skey] = {"hash": h,
                                              "text": llm.interpret(cfg["key"], model, title, what, data)}
                st.rerun()
            st.caption(clean(f"Generated by {model} from this output's values only. Review before use."))
        else:
            if st.button("Interpret this output", key=f"gen_{block_id}"):
                with st.spinner("Interpreting..."):
                    st.session_state[skey] = {"hash": h,
                                              "text": llm.interpret(cfg["key"], model, title, what, data)}
                st.rerun()


def chat_panel(chat_id: str, title: str, what: str, data, suggestions: list[str] | None = None,
               system: str | None = None, assistant_avatar: str | None = None,
               heading: str | None = None) -> None:
    """A grounded, memory-keeping chat scoped to one output (or tab)."""
    cfg = _cfg()
    st.markdown(heading or f"##### Ask about: {clean(title)}")
    if not cfg.get("key"):
        st.caption(clean("Add your OpenAI API key in the sidebar to ask questions about this output."))
        return
    model = cfg.get("model", llm.DEFAULT_MODEL)
    mkey = f"chat_{chat_id}"
    st.session_state.setdefault(mkey, [])

    if suggestions:
        st.caption(clean("Try: " + "  |  ".join(suggestions)))

    for m in st.session_state[mkey]:
        av = assistant_avatar if m["role"] == "assistant" else None
        with st.chat_message(m["role"], avatar=av):
            st.markdown(clean(m["content"]))

    with st.form(key=f"form_{chat_id}", clear_on_submit=True):
        q = st.text_input("Your question", key=f"in_{chat_id}",
                          placeholder="Ask only about the values shown in this output...")
        col1, col2 = st.columns([1, 1])
        send = col1.form_submit_button("Send")
        clear = col2.form_submit_button("Clear chat")

    if clear:
        st.session_state[mkey] = []
        st.rerun()
    if send and q and q.strip():
        st.session_state[mkey].append({"role": "user", "content": q.strip()})
        with st.spinner("Thinking..."):
            reply = llm.chat(cfg["key"], model, st.session_state[mkey], title, what, data, system=system)
        st.session_state[mkey].append({"role": "assistant", "content": reply})
        st.rerun()
